name: Update timezones.json Automatically

on:
  push:
    branches:
      - ehradio
  workflow_dispatch:

jobs:
  update-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download and update timezones.json if changed
        run: |
          TARGET_FILE="data/www/timezones.json"
          TMP_FILE="${TARGET_FILE}.tmp"
          URL="https://github.com/trip5/timezones.json/raw/refs/heads/master/timezones.json"
          mkdir -p data/www
          curl -L -s -o "$TMP_FILE" "$URL"
          if [ ! -f "$TARGET_FILE" ] || ! cmp -s "$TARGET_FILE" "$TMP_FILE"; then
            echo "timezones.json is new or has changed. Updating."
            mv "$TMP_FILE" "$TARGET_FILE"
          else
            echo "timezones.json is unchanged."
            rm "$TMP_FILE"
          fi

      - name: Commit updated files if changed
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add data/www/timezones.json
          if ! git diff --cached --quiet; then
            git commit -m "Update JSON automatically from external sources"
            git push
          else
            echo "No changes to commit for JSON files."
          fi

# git add data/www/rb_srvrs.json data/www/timezones.json.gz